version: 1.0.{build}

install: 
  - choco install autohotkey.install

build_script:
  - cmd: >-
      "C:\Program Files\AutoHotkey\Compiler\Ahk2Exe.exe" /in C:\projects\munager\feedback.ahk

      "C:\Program Files\AutoHotkey\Compiler\Ahk2Exe.exe" /in C:\projects\munager\munager.ahk